name: ecommerce_assets
description: Ecommerce Assets
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.7
  lottie: ^2.5.0


dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: EcommerceAssets

  fonts:
    enabled: false
  colors:
    enabled: false


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
